name: Run Snakemake and render site
run-name: ${{ github.event.repository.updated_at }} run
on: [push]
jobs:
  Render-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Snakemake workflow
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: "."
          snakefile: "Snakefile"
          args: "--cores 2 --use-conda --conda-cleanup-pkgs cache"
          stagein: ""
      # - name: "Deploy to gh-pages"
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs
      - run: echo "ğŸ This job's status is ${{ job.status }}."
